#!/bin/bash
. "$(dirname $0)/../lib/testing.bash"

calc="$2/bin/calc"

# correct expressions
test_out "$1:1" "$calc" "0" "0" && \
test_out "$1:2" "$calc" "1" "1" && \
test_out "$1:3" "$calc" "1+2*3" "7" && \
test_out "$1:4" "$calc" "0*1+2+3*4*5+6*7+8*0" "104" && \

# incorrect expressions
test_err "$1:6" "$calc" "1+" "Unexpected token END at 2" && \
test_err "$1:7" "$calc" "1++" "Unexpected token ADD at 2" && \
test_err "$1:8" "$calc" "1+*" "Unexpected token MUL at 2" && \
test_err "$1:9" "$calc" "+1" "Unexpected token ADD at 0"
