#!/bin/bash
. "$(dirname $0)/../lib/testing.bash"

calc="$2/bin/calc"

# correct brackets
test_out "$1:1" "$calc" "(0)" "0" && \
test_out "$1:2" "$calc" "(((((1)))))" "1" && \
test_out "$1:3" "$calc" "(1+2)*3" "9" && \
test_out "$1:4" "$calc" "(1+(2+((3)*4*((5+(6*7))))))" "567" && \

# incorrect brackets
test_err "$1:5" "$calc" "((0)" "Unexpected token END at 4" && \
test_err "$1:6" "$calc" "(0))" "Unexpected token RBR at 3" && \

# multi-digit numbers
test_out "$1:7" "$calc" "0" "0" && \
test_out "$1:8" "$calc" "42" "42" && \
test_out "$1:9" "$calc" "12345" "12345" && \

# spacing
test_out "$1:10" "$calc" "  1" "1" && \
test_out "$1:11" "$calc" "1  " "1" && \
test_out "$1:12" "$calc" " 1  +2*  3+  (  (5 * 3 )) " "22" && \

# division and subtraction
test_out "$1:13" "$calc" "4-2" "2" && \
test_out "$1:14" "$calc" "0-2" "-2" && \
test_out "$1:14" "$calc" "8/2" "4" && \
test_out "$1:14" "$calc" "0/2" "0" && \
test_err "$1:14" "$calc" "2/0" "Division by 0."
